- name: RuuviTag_Jaakaappi_Temperature
  state_topic: "RuuviPublisherData/Jaakaappi"
  unit_of_measurement: "Â°C"
  device_class: "temperature"
  value_template: "{{ value_json.temperature|float|round(1) }}"
- name: RuuviTag_Jaakaappi_Humidity
  state_topic: "RuuviPublisherData/Jaakaappi"
  unit_of_measurement: "%"
  device_class: "humidity"
  value_template: "{{ value_json.humidity|float|round(1) }}"